[build]
builder = "DOCKERFILE"

[deploy]
preDeployCommand = ["/opt/operately/bin/predeploy.sh"]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
requiredMountPath = "/media"
